import tkinter as tk


class Task:
    def __init__(self, name, priority, min_time, color):
        self.name = name
        self.priority = priority
        self.min_time = min_time
        self.color = color

class ToolTip:
    """Manages floating info bubbles for canvas elements."""
    def __init__(self, canvas):
        self.canvas = canvas
        self.tooltip_window = None
        self.data = {}
        
        self.canvas.tag_bind("task_panel", "<Enter>", self.show_tooltip)
        self.canvas.tag_bind("task_panel", "<Leave>", self.hide_tooltip)
        self.canvas.tag_bind("task_panel", "<Motion>", self.move_tooltip)

    def register(self, item_id, text):
        self.data[item_id] = text

    def show_tooltip(self, event):
        current = self.canvas.find_withtag("current")
        if not current:
            return
        
        item_id = current[0]
        text = self.data.get(item_id)
        if not text:
            return
        
        x, y = event.x_root + 15, event.y_root + 15
        self.tooltip_window = tk.Toplevel(self.canvas)
        self.tooltip_window.wm_overrideredirect(True)
        self.tooltip_window.wm_geometry(f"+{x}+{y}")
        
        label = tk.Label(self.tooltip_window, text=text, background="#ffffe0", 
                         relief="solid", borderwidth=1, justify="left", font=("Arial", 9))
        label.pack()

    def hide_tooltip(self, event):
        if self.tooltip_window:
            self.tooltip_window.destroy()
            self.tooltip_window = None

    def move_tooltip(self, event):
        if self.tooltip_window:
            x, y = event.x_root + 15, event.y_root + 15
            self.tooltip_window.wm_geometry(f"+{x}+{y}")

def get_clear_timeline_bounds(tasks):
    """Simulates a clear timeline to find the maximum theoretical debt/excess."""
    time_now = 0
    actual_times = {t.name: 0 for t in tasks}
    total_priority = sum(t.priority for t in tasks)
    
    state_seen = set()
    max_v = {t.name: -float('inf') for t in tasks}
    
    while True:
        state = tuple(time_now * t.priority - actual_times[t.name] * total_priority for t in tasks)
        if state in state_seen:
            break
        state_seen.add(state)
        
        best_task = None
        best_v = -float('inf')
        
        for t in tasks:
            v = t.priority * time_now - actual_times[t.name] * total_priority
            max_v[t.name] = max(max_v[t.name], v)
                
            if v > best_v:
                best_v = v
                best_task = t
                
        if best_task is None:
            break
            
        time_now += best_task.min_time
        actual_times[best_task.name] += best_task.min_time
        
    return max_v

def get_schedule_rules(tasks, pre_placed=None, periods=None):
    """
    Simulates the schedule with constraints (pre-placed tasks, periods, decay).
    Returns a finite list of rules (prefix blocks and repeating cycle blocks).
    Stops at 50 rules if aperiodic.
    """
    if pre_placed is None: pre_placed = []
    if periods is None: periods = []
    
    total_priority = sum(t.priority for t in tasks)
    clear_max_v = get_clear_timeline_bounds(tasks)
    
    time_now = 0
    actual_times = {t.name: 0 for t in tasks}
    
    # We now track the exact magnitude of the debt generated by blocks, and when it started
    excess_tracker = {t.name: {'start_time': None, 'max_excess': 0} for t in tasks}
    
    raw_steps = []
    state_seen = {}
    
    pre_placed_sorted = sorted(pre_placed, key=lambda x: x['start'])
    
    epsilon = 1.0
    decay_rate = 0.95
    
    while len(raw_steps) < 50:
        # Check pre-placed tasks first
        active_pre = None
        for p in pre_placed_sorted:
            if p['start'] <= time_now < p['start'] + p['duration']:
                active_pre = p
                break
                
        if active_pre:
            jump = (active_pre['start'] + active_pre['duration']) - time_now
            raw_steps.append({
                'name': active_pre['name'], 
                'duration': jump, 
                'color': active_pre.get('color', '#DDDDDD')
            })
            time_now += jump
            continue

        # Determine allowed tasks based on periods
        allowed_tasks = tasks
        if periods:
            for p in periods:
                if p['start'] <= time_now < p['end']:
                    allowed_tasks = [t for t in tasks if t.name in p['allowed']]
                    break
        
        if not allowed_tasks:
            break
        
        future_pre = any(p['start'] >= time_now for p in pre_placed_sorted)
        if not future_pre and not periods:
            cycle_state = tuple(time_now * t.priority - actual_times[t.name] * total_priority for t in tasks)
            if cycle_state in state_seen:
                cycle_start = state_seen[cycle_state]
                return compress(raw_steps[:cycle_start]), compress(raw_steps[cycle_start:])
            state_seen[cycle_state] = len(raw_steps)

        # Select the next best task
        best_task = None
        best_key = (-float('inf'), -float('inf'))
        
        for t in allowed_tasks:
            v_raw = t.priority * time_now - actual_times[t.name] * total_priority
            excess = v_raw - clear_max_v[t.name]
            
            if excess > 0:
                # Capture the moment the task starts building actionable debt
                if excess_tracker[t.name]['start_time'] is None:
                    excess_tracker[t.name]['start_time'] = time_now
                
                # We track the PEAK debt (so it freezes while they pay it off)
                if excess > excess_tracker[t.name]['max_excess']:
                    excess_tracker[t.name]['max_excess'] = excess
                    
                distance = time_now - excess_tracker[t.name]['start_time']
                decay = decay_rate ** distance
                
                # Epsilon rounding: completely ignore tiny lingering pieces of debt
                decayed_remaining = excess_tracker[t.name]['max_excess'] * decay
                if decayed_remaining < epsilon:
                    decayed_remaining = 0
                    
                # We subtract the ignored debt from the raw v to maintain precise alternating behavior
                ignored_debt = excess_tracker[t.name]['max_excess'] - decayed_remaining
                v_eff = v_raw - ignored_debt
            else:
                # Not in an excess state; reset tracker
                excess_tracker[t.name]['start_time'] = None
                excess_tracker[t.name]['max_excess'] = 0
                v_eff = v_raw
                
            sort_key = (v_eff, v_raw)
            
            if sort_key > best_key:
                best_key = sort_key
                best_task = t
                
        if best_task is None:
            break
            
        raw_steps.append({
            'name': best_task.name,
            'duration': best_task.min_time,
            'color': best_task.color
        })
        actual_times[best_task.name] += best_task.min_time
        time_now += best_task.min_time

    return compress(raw_steps), []

def compress(steps):
    """Compress identical sequential tasks into combined duration blocks."""
    blocks = []
    for step in steps:
        if blocks and blocks[-1]['name'] == step['name']:
            blocks[-1]['duration'] += step['duration']
        else:
            blocks.append({
                'name': step['name'],
                'duration': step['duration'],
                'color': step['color']
            })
    return blocks

def generate_schedule(prefix_blocks, cycle_blocks, total_duration):
    """Generates the timeline up to 'total_duration' by unrolling the finite rules."""
    schedule = []
    time_now = 0
    
    def append_block(block_template):
        nonlocal time_now
        if schedule and schedule[-1]['name'] == block_template['name']:
            schedule[-1]['duration'] += block_template['duration']
        else:
            schedule.append({
                'name': block_template['name'],
                'start': time_now,
                'duration': block_template['duration'],
                'color': block_template['color']
            })
        time_now += block_template['duration']

    for block in prefix_blocks:
        if time_now >= total_duration:
            break
        append_block(block)
        
    if not cycle_blocks:
        return schedule 
        
    while time_now < total_duration:
        for block in cycle_blocks:
            if time_now >= total_duration:
                break
            append_block(block)
            
    return schedule

def copy_to_clipboard(root, title, prefix_blocks, cycle_blocks):
    lines = [title, "Rules:"]
    if prefix_blocks:
        lines.append("Prefix:")
        for block in prefix_blocks:
            lines.append(f"- task {block['name']} {block['duration']}min")
    if cycle_blocks:
        lines.append("Cycle:")
        for block in cycle_blocks:
            lines.append(f"- task {block['name']} {block['duration']}min")
        lines.append("- repeat")
    else:
        lines.append("(No cycle found - capped by rule limit or bounded timeline)")
        
    clipboard_text = "\n".join(lines)
    root.clipboard_clear()
    root.clipboard_append(clipboard_text)

def draw_schedules(root, canvas, test_cases, window_width=900):
    y_offset = 20
    px_per_min = 4
    margin_left = 90  
    margin_right = 30
    row_duration = (window_width - margin_left - margin_right) // px_per_min
    row_height = 40
    row_spacing = 20
    
    tooltip = ToolTip(canvas)
    
    for title, tasks, total_duration, pre_placed, periods in test_cases:
        prefix_blocks, cycle_blocks = get_schedule_rules(tasks, pre_placed, periods)
        schedule = generate_schedule(prefix_blocks, cycle_blocks, total_duration)
        
        btn = tk.Button(canvas, text="Copy\nRules", cursor="hand2",
                        command=lambda t=title, p=prefix_blocks, c=cycle_blocks: copy_to_clipboard(root, t, p, c))
        canvas.create_window(15, y_offset, window=btn, anchor="nw")
        
        txt_id = canvas.create_text(margin_left, y_offset, text=title, font=("Arial", 11, "bold"), anchor="nw")
        bbox = canvas.bbox(txt_id)
        y_offset = bbox[3] + 20 
        
        max_row_idx = 0
        for block in schedule:
            block_start = block['start']
            remaining = block['duration']
            
            original_start = block['start']
            original_end = original_start + block['duration']
            hover_info = f"Task {block['name']}\nStart: {original_start}\nEnd: {original_end}"
            
            while remaining > 0:
                row_idx = block_start // row_duration
                start_in_row = block_start % row_duration
                time_in_row = min(remaining, row_duration - start_in_row)
                
                x1 = margin_left + start_in_row * px_per_min
                x2 = margin_left + (start_in_row + time_in_row) * px_per_min
                y1 = y_offset + row_idx * (row_height + row_spacing)
                y2 = y1 + row_height
                
                rect_id = canvas.create_rectangle(x1, y1, x2, y2, fill=block['color'], 
                                                  outline="black", tags="task_panel")
                tooltip.register(rect_id, hover_info)
                
                if (x2 - x1) > 30:
                    text_id = canvas.create_text((x1 + x2) / 2, (y1 + y2) / 2, 
                                                 text=block['name'], font=("Arial", 10), tags="task_panel")
                    tooltip.register(text_id, hover_info)
                
                remaining -= time_in_row
                block_start += time_in_row
                max_row_idx = max(max_row_idx, row_idx)
                
        y_offset += (max_row_idx + 1) * (row_height + row_spacing) + 40
        
    canvas.config(scrollregion=(0, 0, window_width, y_offset))


def main():
    test_cases = [
        (
            "Test 1: Normal 50/50 Split (10min each)\n-> Pure Periodic Cycle",
            [
                Task("A", priority=50, min_time=10, color="#FF9999"),
                Task("B", priority=50, min_time=10, color="#99CCFF")
            ],
            180, [], []
        ),
        (
            "Test 2: Pre-placed event interrupts timeline\n-> A and B catch up, but debt decay prevents a massive monopoly block.",
            [
                Task("A", priority=50, min_time=10, color="#FF9999"),
                Task("B", priority=50, min_time=10, color="#99CCFF")
            ],
            240, 
            [{'name': 'MAINTENANCE', 'start': 40, 'duration': 60, 'color': '#CCCCCC'}], 
            []
        ),
        (
            "Test 3: Periods constraint\n-> Task C is only allowed between t=0 and t=100. Caps at 50 rules.",
            [
                Task("A", priority=40, min_time=10, color="#FF9999"),
                Task("B", priority=40, min_time=10, color="#99CCFF"),
                Task("C", priority=20, min_time=10, color="#99FF99")
            ],
            300, 
            [], 
            [{'start': 0, 'end': 100, 'allowed': ['A', 'B', 'C']}, {'start': 100, 'end': 9999, 'allowed': ['A', 'B']}]
        ),
        (
            "Test 4: Three Tasks (A: 50% 20m, B: 30% 10m, C: 20% 15m)",
            [
                Task("A", priority=50, min_time=20, color="#FF9999"),
                Task("B", priority=30, min_time=10, color="#99CCFF"),
                Task("C", priority=20, min_time=15, color="#99FF99")
            ],
            400,
            [], 
            []
        )
    ]

    root = tk.Tk()
    root.title("Task Scheduler Timeline with Constraints")
    root.geometry("950x700")

    canvas = tk.Canvas(root, bg="white")
    vbar = tk.Scrollbar(root, orient=tk.VERTICAL, command=canvas.yview)
    canvas.configure(yscrollcommand=vbar.set)

    vbar.pack(side=tk.RIGHT, fill=tk.Y)
    canvas.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)

    def _on_mousewheel(event):
        if getattr(event, 'num', 0) == 4 or event.delta > 0:
            canvas.yview_scroll(-1, "units")
        elif getattr(event, 'num', 0) == 5 or event.delta < 0:
            canvas.yview_scroll(1, "units")

    canvas.bind_all("<MouseWheel>", _on_mousewheel) 
    canvas.bind_all("<Button-4>", _on_mousewheel)   
    canvas.bind_all("<Button-5>", _on_mousewheel)   

    draw_schedules(root, canvas, test_cases, window_width=900)
    root.mainloop()

if __name__ == "__main__":
    main()